criaCartao(
    'SE LIGA!!!!! P01 <br> PROJETO DE VIDA', 
    'DETERMINAÇÃO E PERSISTÊNCIA?', 
    'SÃO QUALIDADES IMPORTANTES PARA ALCANÇAR O SUCESSO. MANTER A MOTIVAÇÃO, SEM PENSAR EM DESISTIR.'
)

criaCartao(
    'SE LIGA!!!!! P02 <br> PROJETO DE VIDA', 
    'ORGANIZAÇÃO E FOCO', 
    'SÃO QUALIDADES IMPRESCENDÍVEIS PARA SE TER UMA VIDA EQUILIBRADA E PRODUTIVA.'
)

criaCartao(
    'SE LIGA!!!!! P03 <br> PROJETO DE VIDA', 
    'GESTÃO DE TEMPO?', 
    'É UMA METOLODOGIA QUE CONFERE ORGANIZAÇÃO, PLANEJAMENTO E PRODUTIVIDADE À ROTINA.'
)

criaCartao(
    'SE LIGA!!!!! P04 <br> PROJETO DE VIDA', 
    'DECISÃO RESPONSÁVEL?', 
    'É O PROCESSO DE ESCOLHA ENTRE DIVERSAS POSSIBILIDADES.'
)

criaCartao(
    'SE LIGA!!!!! P05 <br> PROJETO DE VIDA', 
    'RESILIÊNCIA?', 
    'É A CAPACIDADE DE ENFRENTAR E SUPERAR ADVERSIDADES.'
)

criaCartao(
    'SE LIGA!!!!! P06 <br> PROJETO DE VIDA', 
    'ASSERTIVIDADE?', 
    'É A HABILIDADE SOCIAL DE FAZER AFIRMAÇÃO DOS PRÓPRIOS DIREITOS, SENTIMENTOS E CRENÇAS DE FORMA CLARA, HONESTA E DIRETA.'
)

criaCartao(
    'SE LIGA!!!!! P07 <br> PROJETO DE VIDA', 
    'HABILIDADES PESSOAIS?', 
    'SÃO AS APTIDÕES E QUALIDADES QUE UM INDIVÍDUO POSSUI.'
)

criaCartao(
    'SE LIGA!!!!! P08 <br> PROJETO DE VIDA', 
    'COMPETÊNCIAS PESSOAIS?', 
    'SÃO ATRIBUTOS E TÉCNICAS QUE O INDIVÍDUO DESENVOLVE PARA EXECUTAR TAREFAS.'
)

criaCartao(
    'SE LIGA!!!!! P09 <br> PROJETO DE VIDA', 
    'HABILIDADE PROFISSIONAL?', 
    'SÃO COMPETÊNCIAS QUE PERMITEM EXECUTAR ATIVIDADES DE MANEIRA EFICIENTE EM CADA ÁREA DE EXECUÇÃO.'
)

criaCartao(
    'SE LIGA!!!!! P10 <br> PROJETO DE VIDA',  
    'PENSAMENTO CRIATIVO?', 
    'É O PROCESSO MENTAL QUE ENVOLVE A GERAÇÃO DE IDEIAS, CONCEITOS E SOLUÇÕES NOVAS E ORIGINAIS.'
)

criaCartao(
    'SE LIGA!!!!! P11 <br> PROJETO DE VIDA', 
    'AUTO CONFIANÇA?', 
    'É A SENSAÇÃO QUE A PESSOA TEM DE SER CAPAZ DE REALIZAR OU ALCANÇAR AQUILO QUE DESEJA.'
)
criaCartao(
    'SE LIGA!!!!! P12 <br> PROJETO DE VIDA',  
    'PROATIVIDADE?', 
    'CARACTERÍSTICA OU COMPORTAMENTO DE UM INDIVÍDUO QUE SE ANTECIPA E SE RESPONSABILIZA PELAS PRÓPRIAS ESCOLHAS E AÇÕES.'
)

criaCartao(
    'SE LIGA!!!!! P13 <br> PROJETO DE VIDA', 
    'INTELIGÊNCIA EMOCIONAL?', 
    'É A CAPACIDADE DE RECONHECER E LIDAR COM AS PRÓPRIAS EMOÇÕES.'
)

criaCartao(
    'SE LIGA!!!!! P14 <br> PROJETO DE VIDA', 
    'COMPROMETIMENTO?', 
    'AÇÃO DE COMPROMETER OU SE COMPROMETER COM ALGO OU ALGUÉM.'
)

criaCartao(
    'SE LIGA!!!!! P15 <br> PROJETO DE VIDA', 
    'CAPACIDADE DE INOVAÇÃO?', 
    'É UM PROCESSO DINÂMICO QUE PERMITE APLICAR A CIÊNCIA E A TECNOLOGIA PARA O DESENVOLVIMENTO DO MERCADO PRODUTIVO E SOCIAL.'
)

criaCartao(
    'SE LIGA!!!!! P16 <br> PROJETO DE VIDA', 
    'PENSAMENTO CRÍTICO?', 
    'É UMA AVALIAÇÃO VOLUNTÁRIO DIANTE DE UM FATO, COMENTÁRIO OU EXPERÊNCIA/CONTEÚDO, QUE USA ARGUMENTOS PARA CHEGAR A UMA RESPOSTA.'
)